### ISSUE TITLE
impl From<Url> for StreamerUri

### ISSUE THREAD

**Issue by carlocorradini** [SeaQL/sea-streamer#26]
## Motivation

Currently we cannot convert a `Url` into a `StreamerUri` unless we transform it back to a `String`.

## Proposed Solutions

```rs
impl From<Url> for StreamerUri {
    fn from(value: Url) -> Self {
        Self { nodes: vec![value] }
    }
}
```

## Additional Information

Maybe in the future accept a generic that `impl IntoStreamerUri`. Something like _sea-orm_.

**Comment by tyt2y3** [comment]
agreed!

**Comment by carlocorradini** [comment]
I'll try a PR
