### ISSUE TITLE
Why only `stdio` mode is returned, not other backend modes?

### ISSUE THREAD

**Issue by holmofy** [SeaQL/sea-streamer#34]
https://github.com/SeaQL/sea-streamer/blob/34e96914761bb6cf1ccde68d4aaa1fe0758ae246/sea-streamer-socket/src/consumer_options.rs#L120

```rust
    fn mode(&self) -> SeaResult<&ConsumerMode> {
        self.stdio.mode().map_err(map_err)
    }

    /// Get currently set consumer group; may return `StreamErr::ConsumerGroupNotSet`.
    fn consumer_group(&self) -> SeaResult<&ConsumerGroup> {
        self.stdio.consumer_group().map_err(map_err)
    }
```

**Comment by tyt2y3** [comment]
the stdio is just used a standin, it's mode is actually applied to other backends IIRC

**Comment by tyt2y3** [comment]
ah okay, so the `mode` config is set to all backends, including `stdio`, so returning only stdio here is not wrong. the problem though, is we can't compile without the stdio backend. it does not fetch many more dependencies, but still may we should make it possible to compile without the stdio backend.
